import '@testing-library/jest-dom/vitest';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { MarkdownMessage } from '../../src/renderer/components/MarkdownMessage';

describe('MarkdownMessage', () => {
  let clipboardDescriptor: PropertyDescriptor | undefined;
  let execCommandDescriptor: PropertyDescriptor | undefined;

  beforeEach(() => {
    clipboardDescriptor = Object.getOwnPropertyDescriptor(navigator, 'clipboard');
    execCommandDescriptor = Object.getOwnPropertyDescriptor(document, 'execCommand');
  });

  afterEach(() => {
    restoreDescriptor(navigator, 'clipboard', clipboardDescriptor);
    restoreDescriptor(document, 'execCommand', execCommandDescriptor);
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  it('copies the exact contents of a fenced code block from its inline copy button', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText }
    });

    render(<MarkdownMessage text={['```asm', 'main_loop:', '  CLRWDT', '```'].join('\n')} />);

    fireEvent.click(screen.getByRole('button', { name: '复制代码' }));

    await waitFor(() => {
      expect(writeText).toHaveBeenCalledWith('main_loop:\n  CLRWDT');
    });
    expect(screen.getByText('已复制')).toBeInTheDocument();
  });

  it('uses the document copy command immediately when the async clipboard never settles', async () => {
    const writeText = vi.fn(() => new Promise<void>(() => undefined));
    const execCommand = vi.fn().mockReturnValue(true);
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText }
    });
    Object.defineProperty(document, 'execCommand', {
      configurable: true,
      value: execCommand
    });

    render(<MarkdownMessage text={['```asm', 'main_loop:', '  CLRWDT', '```'].join('\n')} />);

    fireEvent.click(screen.getByRole('button', { name: '复制代码' }));

    await waitFor(() => {
      expect(execCommand).toHaveBeenCalledWith('copy');
    });
    expect(writeText).not.toHaveBeenCalled();
    expect(screen.getByText('已复制')).toBeInTheDocument();
  });

  it('shows a failure state instead of staying idle when every copy strategy fails', async () => {
    vi.useFakeTimers();
    const writeText = vi.fn(() => new Promise<void>(() => undefined));
    const execCommand = vi.fn().mockReturnValue(false);
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText }
    });
    Object.defineProperty(document, 'execCommand', {
      configurable: true,
      value: execCommand
    });

    render(<MarkdownMessage text={['```asm', 'main_loop:', '  CLRWDT', '```'].join('\n')} />);

    fireEvent.click(screen.getByRole('button', { name: '复制代码' }));

    await act(async () => {
      await vi.advanceTimersByTimeAsync(1300);
    });

    expect(screen.getByText('复制失败')).toBeInTheDocument();
  });

  it('falls back to the document copy command when the async clipboard is rejected', async () => {
    const writeText = vi.fn().mockRejectedValue(new Error('NotAllowedError'));
    const execCommand = vi.fn().mockReturnValue(true);
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText }
    });
    Object.defineProperty(document, 'execCommand', {
      configurable: true,
      value: execCommand
    });

    render(<MarkdownMessage text={['```asm', 'main_loop:', '  CLRWDT', '```'].join('\n')} />);

    fireEvent.click(screen.getByRole('button', { name: '复制代码' }));

    await waitFor(() => {
      expect(execCommand).toHaveBeenCalledWith('copy');
    });
    expect(screen.getByText('已复制')).toBeInTheDocument();
  });

  it('emits the fenced code contents from the inline normalize button', () => {
    const normalize = vi.fn();

    render(<MarkdownMessage text={['```asm', 'main_loop:', '  CLRWDT', '```'].join('\n')} onNormalizeCode={normalize} />);

    fireEvent.click(screen.getByRole('button', { name: '规范化' }));

    expect(normalize).toHaveBeenCalledWith('main_loop:\n  CLRWDT');
  });

  it('shows a green normalized status instead of a normalize button for validated ASM output', () => {
    const normalize = vi.fn();

    render(
      <MarkdownMessage
        text={[
          '```asm',
          '; HK64S8x single-file ASM generated by ASM Agent.',
          '; File: main.asm',
          '; Static check: passed built-in instruction/register validation before display.',
          'main_loop:',
          '  CLRWDT',
          '```'
        ].join('\n')}
        onNormalizeCode={normalize}
      />
    );

    expect(screen.getByText('已规范')).toHaveClass('markdown-code-normalized-badge');
    expect(screen.queryByRole('button', { name: '规范化' })).not.toBeInTheDocument();
    expect(normalize).not.toHaveBeenCalled();
  });
});

function restoreDescriptor(target: object, key: string, descriptor: PropertyDescriptor | undefined) {
  if (descriptor) {
    Object.defineProperty(target, key, descriptor);
    return;
  }

  Reflect.deleteProperty(target, key);
}
