import type { GenerationPlan } from '../agent/GenerationPlanner';
import type { GeneratedFile } from '../project/ProjectTypes';
import type { ChipSpec } from '../spec/ChipSpec';
import { parseAsm } from './AsmParser';
import { validateAsm } from './AsmValidator';

export interface SingleAsmFileGeneratorInput {
  requirement: string;
  plan: GenerationPlan;
  spec: ChipSpec;
  fileName?: string;
}

export class SingleAsmFileGenerator {
  generate(input: SingleAsmFileGeneratorInput): GeneratedFile {
    const features = new Set(input.plan.features.map((feature) => feature.toLowerCase()));
    const content = ensureTrailingNewline(
      [
        ...renderHeader(input),
        '',
        'reset_entry:',
        '  CLRWDT',
        '  CALL main_entry',
        '  JMP main_loop',
        '',
        'main_entry:',
        ...(features.has('gpio') ? ['  CALL gpio_init'] : []),
        ...(features.has('timer0') ? ['  CALL timer0_init'] : []),
        ...(features.has('wdt') ? ['  CALL wdt_service'] : []),
        '  RET',
        '',
        'main_loop:',
        '  CLRWDT',
        '  JMP main_loop',
        '',
        ...(features.has('gpio') ? renderGpioInit(input.spec) : []),
        ...(features.has('timer0') ? renderTimer0Init() : []),
        ...(features.has('wdt') ? renderWdtService() : []),
        ...(input.plan.usesInterrupt ? renderInterruptHandler() : [])
      ].join('\n')
    );

    const diagnostics = validateAsm(parseAsm(content), input.spec);
    if (diagnostics.length > 0) {
      throw new Error(
        `Generated ASM failed built-in validation: ${diagnostics
          .map((diagnostic) => `${diagnostic.lineNumber}:${diagnostic.code}`)
          .join(', ')}`
      );
    }

    return {
      path: sanitizeAsmFileName(input.fileName),
      content
    };
  }
}

function renderHeader(input: SingleAsmFileGeneratorInput): string[] {
  return [
    '; HK8S8100X single-file ASM generated by ASM Agent.',
    `; File: ${sanitizeAsmFileName(input.fileName)}`,
    `; Spec: ${input.spec.chipId} v${input.spec.version}`,
    `; Requirement: ${input.requirement.replace(/\r?\n/g, ' ').trim() || 'not specified'}`,
    '; Static check: passed built-in instruction/register validation before display.'
  ];
}

function renderGpioInit(spec: ChipSpec): string[] {
  requireRegister(spec, 'PA_OE');
  requireRegister(spec, 'PA_PIO');

  return [
    'gpio_init:',
    '  MOV A,#0xFF',
    '  MOV PA_OE,A',
    '  MOV A,#0x01',
    '  MOV PA_PIO,A',
    '  RET',
    ''
  ];
}

function renderTimer0Init(): string[] {
  return [
    'timer0_init:',
    '  ; Timer0 timing values must be confirmed before hardware use.',
    '  RET',
    ''
  ];
}

function renderWdtService(): string[] {
  return [
    'wdt_service:',
    '  CLRWDT',
    '  RET',
    ''
  ];
}

function renderInterruptHandler(): string[] {
  return [
    'interrupt_entry:',
    '  CLRWDT',
    '  RETI',
    ''
  ];
}

function requireRegister(spec: ChipSpec, name: string): void {
  if (!spec.registers.some((register) => register.name === name)) {
    throw new Error(`Built-in spec is missing required register: ${name}`);
  }
}

function sanitizeAsmFileName(fileName?: string): string {
  const baseName = (fileName ?? 'main.asm')
    .replace(/\\/g, '/')
    .split('/')
    .pop()
    ?.trim()
    .replace(/\.asm$/i, '')
    .replace(/[^A-Za-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return `${baseName || 'main'}.asm`;
}

function ensureTrailingNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}
